export const ConstManager = {
    gameSection: document.getElementById('gameSectionBox'),
    rulesSection: document.getElementById('rulesBox'),
    rulesText: document.getElementById('rulesTextBox'),
    settingsSection: document.getElementById('settingsBox'),
    leaderboardSection: document.getElementById('leaderboardBox'),
    playerListDiv: document.getElementById('playerList'),
    burgerSection: document.getElementById('burgerOptionsBox'),
    avocadoHoles: document.querySelectorAll('.avocadoHole'),
    scoreDisplay: document.querySelector('.scoreText'),
    startButton: document.querySelector('.start'),
    pauseButton: document.querySelector('.pause'),
    resumeButton: document.querySelector('.resume'),
    connectBG: document.getElementById('connectBG'),
    playerNameInput: document.getElementById('playerNameInput'),
    nameInput: document.getElementById('nameInput'),
    nameOutput: document.getElementById('nameOutput'),
    playerName: document.getElementById('playerName'),
    playerHighscore: document.getElementById('playerHighScore'),
    playerRegistered: false,
    navLeftBox: document.getElementById('navLeftBox'),
    timerText: document.getElementById('timerText'),
    gridContainer: document.getElementById('gridContainer'),
    startButton: document.getElementById('startButton'),
    pauseButton: document.getElementById('pauseButton'),
    gameRunning: false,
    easyButton: document.getElementById('easyButton'),
    mediumButton: document.getElementById('mediumButton'),
    hardButton: document.getElementById('hardButton'),
    currentDiff: document.getElementById('currentDiff'),
};

export const VarManager = {
    score: 0,
    isPaused: false,
    timer: 30,
    timerInterval: 1000,
    colors: ['#A7C7E7', '#FAA0A0', '#FAC898'],
}

